### ISSUE TITLE
memorable and consistent urls for extensions

### ISSUE THREAD

**Issue by maxandersen** [quarkusio/extensions.quarkus.io#52]
currently we get: `http://quarkus.io/extensions.quarkus.io/io-quarkus_quarkus-agroal` for an extension.

mix of - and _'s

would it not be more natural to use what maven central uses:

`http://quarkus.io/extensions.quarkus.io/io.quarkus/quarkus-agroal` ?

**Comment by holly-cummins** [comment]
I agree the mix of - and _ isn't that great. 

I thought that it would be technically hard to make separating folders, but in fact it's not, so I've done that. (Turns out slugs can have slashes, but it's not so easy to search for, because there's a lot of hits in there about molluscs and whether slugs have legs.)

In #19, when I switched to using more qualified and maven-like URLs, I deliberately replaced '.' with '-'. Although dots are allowed in URLs, I thought there might be undesirable consequences and some technical risk. Sadly, my code comment doesn't say exactly *what* technical risk. Perhaps it was just that the group id then looks like a domain name. I also thought it looked weird to have a mix of dots and dashes - eg `io.quarkiverse.artemis/quarkus-artemis-core`. 

But since that's what maven does, I will do the same.
